### Welcome
GET http://localhost:8080/api/v1
Content-Type: application/json

### Signup
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
    "first_name": "Ezekiel",
    "last_name": "Olubo",
    "email": "ifeoluwa@olubo.com",
    "password": "somepassword123"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "ifeoluwa@olubo.com",
    "password": "somepassword123"
}
