### Create Order
POST http://localhost:8080/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzU3NjU0MDUsImV4cCI6MTczNTc2OTAwNX0.6A2nD2Nv6ufZ0i-eRTCl575BvwOyWjeaYa-AUOuQotc

{
    "name": "Order 3",
    "description": "This is the second order",
    "specifications": "This is the second order specifications",
    "quantity": 10,
    "due_date": "2021-10-01"
}

### Get Order
GET http://localhost:8080/api/v1/order/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzU3NDMwNjAsImV4cCI6MTczNTc0NjY2MH0.-57PRj5z15zSr7qTPQslIcnJScrGRE5RHWL5FjgrJF0

### Get All Orders
GET http://localhost:8080/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzU3NDMwNjAsImV4cCI6MTczNTc0NjY2MH0.-57PRj5z15zSr7qTPQslIcnJScrGRE5RHWL5FjgrJF0

### Update Order
PATCH http://localhost:8080/api/v1/order/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzU3NDMwNjAsImV4cCI6MTczNTc0NjY2MH0.-57PRj5z15zSr7qTPQslIcnJScrGRE5RHWL5FjgrJF0

{
    "name": "Order 1 Update",
    "description": "This is the first order update",
    "specifications": "This is the first order specifications update"
}

### Cancel Order
PATCH http://localhost:8080/api/v1/order/3/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzU3NjU0MDUsImV4cCI6MTczNTc2OTAwNX0.6A2nD2Nv6ufZ0i-eRTCl575BvwOyWjeaYa-AUOuQotc