-- AlterTable
ALTER TABLE `Order` ADD COLUMN `closing_summary` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('REVIEWING', 'PROCESSING', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'REVIEWING';

-- CreateTable
CREATE TABLE `Chat` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `message` VARCHAR(191) NOT NULL,
    `is_from_customer` BOOLEAN NOT NULL,
    `order_id` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Chat` ADD CONSTRAINT `Chat_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `Order`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
